In [1]:
import os
import pandas as pd
import numpy as np
import shutil


import torch
from sklearn.model_selection import train_test_split
from torch_geometric.data import Data, InMemoryDataset

from utils import load_and_filter_dataset, one_hot_encode_sequence, create_graph_from_sequence
from dataset import PiRNADataset

import networkx as nx
import matplotlib.pyplot as plt

In [2]:
data = load_and_filter_dataset("data\DASHR2_GEO_hg38_sequenceTable_export.csv", save_filtered=True)

<>:1: SyntaxWarning: invalid escape sequence '\D'
<>:1: SyntaxWarning: invalid escape sequence '\D'
C:\Users\lenovo\AppData\Local\Temp\ipykernel_11668\2234487913.py:1: SyntaxWarning: invalid escape sequence '\D'
  data = load_and_filter_dataset("data\DASHR2_GEO_hg38_sequenceTable_export.csv", save_filtered=True)
c:\Users\lenovo\Desktop\RNAGEN\utils.py:19: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support sep=None with delim_whitespace=False; you can avoid this warning by specifying engine='python'.
  df = pd.read_csv(file_path, sep=None, header=None)


Dataset Summary (Before Filtering):
  Total entries: 65156
  RNA types: 13
rnaClass
piRNA           50397
snRNA            4509
miRNAprimary     1881
rRNA             1840
scRNA            1420
mir-3p            959
mir-5p            957
mir-5p3pno        897
tRNA              631
tRF3              631
tRF5              631
snoRNA            402
rnaClass            1
Name: count, dtype: int64
-----------------------------------------
Filtered Dataset:
  Total piRNAs with length 26–32: 50397
  Unique piRNA IDs: 23116
  Length range in filtered data: 26.0 - 32.0
Filtered data saved to data/filtered_piRNAs.csv


In [3]:
output_dir = "dataset/processed"
os.makedirs(output_dir, exist_ok=True)
    
dataset = PiRNADataset(root=output_dir, df=data)
    
print("\nVerifying Dataset:")
print(f"Number of graphs: {len(dataset)}")
    
nucleotides = ['A', 'C', 'G', 'U', 'X']
for idx in [0, 10, 100]:  
    graph = dataset[idx]
    sequence = data.iloc[idx]['seq']
    decoded = ''.join([nucleotides[int(torch.argmax(row))] for row in graph.x])
    print(f"\nGraph {idx} (Sequence: {sequence})")
    print("Node Features Shape:", graph.x.shape)
    print("Node Features (first 5 rows):")
    print(graph.x[:5])
    print("Edge Indices Shape:", graph.edge_index.shape)
    print("Edge Indices (first 10 columns):")
    print(graph.edge_index[:, :10])
    print("Decoded Sequence:", decoded)
    print("Length Attribute:", graph.y.item())

Processing...


Processing dataset...
Created 50397 graphs.
Dataset saved to dataset\processed\processed\piRNA_graphs.pt

Verifying Dataset:
Number of graphs: 50397

Graph 0 (Sequence: UCUACAAGGAUAAUCUGACCUGCAGGGU)
Node Features Shape: torch.Size([32, 5])
Node Features (first 5 rows):
tensor([[0., 0., 0., 1., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0.],
        [1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.]])
Edge Indices Shape: torch.Size([2, 62])
Edge Indices (first 10 columns):
tensor([[0, 1, 1, 2, 2, 3, 3, 4, 4, 5],
        [1, 0, 2, 1, 3, 2, 4, 3, 5, 4]])
Decoded Sequence: UCUACAAGGAUAAUCUGACCUGCAGGGUXXXX
Length Attribute: 28.0

Graph 10 (Sequence: UGGUAGGCCCACAACUUCCCUAAGCCAAGC)
Node Features Shape: torch.Size([32, 5])
Node Features (first 5 rows):
tensor([[0., 0., 0., 1., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [1., 0., 0., 0., 0.]])
Edge Indices Shape: torch.Size([2, 62])
Edge Indices (first 10 columns):
ten

Done!
